// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhFo5OuxQWhHPryC4o60mYkGMdYuH1CyM',
    appId: '1:57334423024:web:69b3e730d524e337695135',
    messagingSenderId: '57334423024',
    projectId: 'maternity-helper-app',
    authDomain: 'maternity-helper-app.firebaseapp.com',
    storageBucket: 'maternity-helper-app.appspot.com',
    measurementId: 'G-ZPKJVTR94R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdvJ_P4mtC_ClDDFMNGG6wsxwOz_Dykv8',
    appId: '1:57334423024:android:b334b12c2ca6010a695135',
    messagingSenderId: '57334423024',
    projectId: 'maternity-helper-app',
    storageBucket: 'maternity-helper-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtEC3PF1YwKGcjoAQYiYz5Eg9AK8eA0PE',
    appId: '1:57334423024:ios:ea8d8f28da90512d695135',
    messagingSenderId: '57334423024',
    projectId: 'maternity-helper-app',
    storageBucket: 'maternity-helper-app.appspot.com',
    iosBundleId: 'com.example.maternityhelperap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtEC3PF1YwKGcjoAQYiYz5Eg9AK8eA0PE',
    appId: '1:57334423024:ios:ea8d8f28da90512d695135',
    messagingSenderId: '57334423024',
    projectId: 'maternity-helper-app',
    storageBucket: 'maternity-helper-app.appspot.com',
    iosBundleId: 'com.example.maternityhelperap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhFo5OuxQWhHPryC4o60mYkGMdYuH1CyM',
    appId: '1:57334423024:web:49f8411f0dc1e576695135',
    messagingSenderId: '57334423024',
    projectId: 'maternity-helper-app',
    authDomain: 'maternity-helper-app.firebaseapp.com',
    storageBucket: 'maternity-helper-app.appspot.com',
    measurementId: 'G-D31WS1E61F',
  );
}
